### PR TITLE
Correct placement for the word 'also'

### PR DESCRIPTION
**Pull request by vsopvsop**
Changing the position of the word 'also', like I have suggested will make the flow smoother.

### CODE REVIEW

**Comment by balupton** [comment]
Thanks. Is there a resource for this? I'm concerned this may be a locale preference, as I've never seen also used like this in Australia.

**Comment by Hypercubed** [comment]
As an American English speaker I think it read better before this change.  FWIW.

**Comment by vsopvsop** [comment]
The word “also” means “too” or “in addition.”

Reference: https://oilpatchwriting.wordpress.com/2011/02/04/placement-of-also-in-sentence/

I am not a native speaker of English. That is why even when I knew I can commit directly, I created a PR for others to comment/discuss. Since nobody passed any adverse comments on this PR for last 20 days, I decided to merge. 

It may be a locale preference or personal preference.

Please show the modified sentence to somebody and ask if the sentence is OK. 
Then show them the earlier unmodified sentence. 
Ask them to tell which is less confusing to understand.

Please feel free to roll back the commit if you are convinced. 
Native speaker wins.

**Comment by vsopvsop** [comment]
The word “also” means “too” or “in addition.”

Reference: https://oilpatchwriting.wordpress.com/2011/02/04/placement-of-also-in-sentence/

Replacing "too" in place of "also" in modified sentence, still gives the same meaning.

When running locally, if you want to profile the performance issues TOO, install the [cpuprofiler plugin](https://github.com/pflannery/docpad-plugin-cpuprofiler):

Replacing "in addition" in place of "also" in modified sentence, still gives the same meaning.

When running locally, if you want to profile the performance issues IN ADDITION, install the [cpuprofiler plugin](https://github.com/pflannery/docpad-plugin-cpuprofiler):

Note: Doing the same replacement in unmodified sentence makes that look like this. Please take your pick.

When running locally, if you TOO want to profile the performance issues, install the [cpuprofiler plugin](https://github.com/pflannery/docpad-plugin-cpuprofiler):

When running locally, if you IN ADDITION want to profile the performance issues, install the [cpuprofiler plugin](https://github.com/pflannery/docpad-plugin-cpuprofiler):

**Comment by vsopvsop** [comment]
Or original sentence can be slightly modified like this if one doesn't want to change the placement of 'also'.

If you also want to profile the performance issues when running locally, install the [cpuprofiler plugin](https://github.com/pflannery/docpad-plugin-cpuprofiler):, install the [cpuprofiler plugin](https://github.com/pflannery/docpad-plugin-cpuprofiler):

**Comment by balupton** [comment]
Considering the examples — while "too" and "also" may mean the same, they don't seem completely interchangeable as their position in the sentence is different — the usage that I see here in Australia, and what sounds correct to me, is:

---

"too" is used as an afterthought at the end:

> When running locally, if you want to profile the performance issues too, then install ...

"also" is used at the start:

> When running locally, if you also want to profile the performance issues, then install ..

You can probably use these together:

> When running locally, if you also want to profile the performance issues too, then install ..

---

If the prefix didn't apply, you could do this:

> Also, if you want to profile the performance issues, then install ...

However that means something different than:

> If you also want to profile the performance issues, then install ...

As the first is "also read this", versus "if you also want to".

Doing "too" in either spot, just doesn't work:

> Too, if you want to profile the performance issues, then install ...
> 
> If you too want to profile the performance issues, then install ...

However, "too" and "also" can probably work at the end, but it is confusing to me:

> If you want to profile the performance issues too, then install ...
> 
> If you want to profile the performance issues also, then install ...

---

"in addition" is used like "as well as", where it usually used with comparison to something, also notice the combination of "also":

> When running locally, if you also want to profile the performance issues in addition to the normal benchmarking, then install ...
> 
> When running locally, if you also want to profile the performance issues as well as running the normal benchmarking, then install ...

---

It kind of reminds me of the use of "though" and "although", they mean the same, but their positioning differs:

> Although... I am pretty awesome.
> 
> I am pretty awesome though...

---

@Hypercubed is this what you find in the USA as well?

This seems to be compatible with https://oilpatchwriting.wordpress.com/2011/02/04/placement-of-also-in-sentence/ unless I'm missing something?

**Comment by Hypercubed** [comment]
I have never though that much about the word also.  My feeling is that it should in the origin place.  Adding the "in addition" makes it more clear.

> When running locally, if you also want to profile the performance issues in addition to the normal benchmarking, then install ...

**Pull request merged**
